### ISSUE TITLE
Issues with SSS modules

### ISSUE THREAD

**Issue by alexone69** [MiSTer-devel/TI-99_4A_MiSTer#3]
The core version 2019-02-16 has issues with the following SSS modules:

- Tennis/Micro Tennis (NIceSoft/Databiotics): the ball is moving to the top of the screen at service;
- Tutankham (Parker Brothers): hangs at initial game screen;
- Moon Patrol (Atari): hangs at initial game screen, after the player's selection screen;
- Congo Bongo (Sega Enterprises): the firts level is ok, but the second level is full of garbage and hangs (the same rom is working fine in MAME);
- Miner2049er (Tigervision): the collision with enemies and items are not working. The collision with floor/ramps is working (the same rom is working fine in MAME);
- Mission X (DataEast): hangs at initial game screen, after few seconds;
- Submarine Commander (Thorn EMI): hangs at initial game screen;
- Return to Pirate's Isle (TI / Adventure International): the game title is full of garbage, then it hangs (the same rom is working fine in MAME);
- Buck Rogers, Planet of Zoom (Sega): hangs at launch;
- U-Boat Jagd (saurus): hangs at launch;
- Mancala (DaTaBioTics): hangs at the game screen;
- Red Baron Flight (DaTaBioTics): hangs at launch;
- River Rescue (Thron EMI): hangs at launch;
- Space Patrol (SunWare): hangs at the game screen;
- Lasso (Texas Instruments): hangs at the game screen;
- Space Bandits (Milton Bradley): garbage on the player's selection screen, than hangs. The rom is the patched version that is working fine in MAME;
- Sewermania (Milton Bradley): same as above;
- Meteor Belt (Milton Bradley): same as above;
- Big Foot Milton Bradley: same as above;
- Super Fly (Milton Bradley): same as above.

**Comment by greyrogue** [comment]
https://github.com/MiSTer-devel/TI-99_4A_MiSTer/commit/383f03c0beebc745c520424cca6c1ce923753cb2

**Comment by greyrogue** [comment]
https://github.com/MiSTer-devel/TI-99_4A_MiSTer/commit/0ac7c5f5c1b486abbef540748215fd70a297f452

**Comment by greyrogue** [comment]
Return to Pirate's Isle can be played be selecting the C Rom for both C and D (select D last).

**Comment by greyrogue** [comment]
Tutankham also seems to work if loading the C Rom as both C and D (with D last).  I believe this can also be done by repeating the C Rom throughout the first 64K if loading a single file (combined System/Cart Roms) version.

**Comment by greyrogue** [comment]
https://github.com/MiSTer-devel/TI-99_4A_MiSTer/commit/b1b66ad048c0aed94ca2ecc4a6ab44d6406a049f

**Comment by alexone69** [comment]
The 20191016 update improved the compatibility and now the following games are working fine:

- Tennis/Micro Tennis (NIceSoft/Databiotics);
- Moon Patrol (Atari);
- Mission X (DataEast);
- Space Patrol (SunWare);
- U-Boat Jagd (Saurus)

The following games (all from Milton Bradley):
- Big Foot;
- Meteor Belt;
- Sewermania;
- Space Bandits;
now can start and are playable. Some garbage on the player's selection screen (Use TI Computer Keys/How many Players?) is presents, but now it accept the user's input and permits to start the game. At game over, if you return to the player's selection screen (with BACK) it seems that the input is no more accepted, while simply restarting the game (with REDO) works correctly (experienced in Sewermania, but it should be the same also for the others).

In the game Superfly (from Milton Bradley) although is now possible to start to play, hangs when the superfly is captured (it's not possible to continue to play). It presents also the same garbage at player's selection screen as previous games.

I was not able to test the following games with the indications from greyrogue (C Rom as both C and D, with D last):
- Tutankham (Parker Brothers)
- Return to Pirate's Isle (TI / Adventure International)
My dumps are composed of a C and a G file, not a C and D file. What's the correct loading procedure in this case?

The other games in my previous list still do not work, however I was able to find a disk version for Buck Rogers and Mancala that are working correctly (the SSS modules are hanging at start on MiSTer, while working fine in MAME).


Many thanks to greyrogue for this update! :-)

**Comment by greyrogue** [comment]
Mancala also works by loading C as a D file.  The order is to load the system ROM as a C file, the C file (e.g. mancalaC.bin) as a C file, load the G file (e.g. mancalaG.bin) as a G file, then load the C file (e.g. mancalaC.bin) again but from the menu as a D file.  Again, if you're building a complete file with system ROMs, you should repeat the C file throughout the first 64KB (the C/D section).

I think I have all of the reported issues above fixed in the latest release 20191020.

**Comment by alexone69** [comment]
The 20191020 update improved the compatibility:

- Big Foot, Meteor Belt, Sewermania, Space Bandits. Now the garbage in the selection menu is disappeared.
- Superfly is working perfectly.
- Tutankham, Return to Pirate's Isle and Mancala can be correctly loaded as indicated by Greyrogue.
- Miner2049er is working perfectly.
- Lasso is now working.
- River Rescue is now working.
- Submarine Commander is now working.
- Congo Bongo: the second level is now working fine.
- The SSS version of Buck Rogers is now working.

Only Red Baron Flight still hangs at launch.

Moreover, I've noticed new voices on the menu for Scratchpad RAM, Cart Type and Speech. Could you please provide some more information on them?

Again, many thanks for the excellent work done! It's really apprecated! :-)

**Comment by greyrogue** [comment]
redbaron8.bin seems to work for me (loading as C).  I can select options, and in the plane, I can hold 8 which increases speed and it takes off.  Does it freeze before or after that point for you?

The TI-99/4A only has 256 bytes of Scratchpad RAM.  It's possible to upgrade it to 1KB, however this breaks some games (including Congo Bongo).  I don't know if any programs take advantage of a system with 1KB of scratchpad RAM, but the core as written by speccery uses 1KB.  I just added an option (which is now the default) to use the original amount, which fixes Congo Bongo.

MBX carts have additional circuitry inside them.  I started implementing this thinking it was needed for the MBX carts you listed.  It turns out those carts aren't the ones that need the additional logic, so I the support isn't needed. I left it in there in case anything else needs it.

Speech still only supports reading the built in ROMs.  No audio generation is implemented.  This partial support was causing issues with Lasso, so I disable it by default now.

**Comment by alexone69** [comment]
Thanks for the clarifications for the new menu options.

Red Baron is working fine using the rom with MD5: 6b927f8d2ea2741a86257d91d1d628f9
The version I was using has MD5: a5e2605e41d7424fca1bdfd22efafa4a and is hanging immediatly after selecting the SSS ("2 FOR RED BARON"). This file is working fine in MESS.

Please, let me know if you need such file for debugging.

I think we can consider closed this issue log.

Many thanks for the support provided for the TI99 core!
